### PR TITLE
Add TypeScript declaration

### PR DESCRIPTION
**Pull request by nlap**
Thanks for this package!

This adds types definitions to the public APIs. All of the examples in the readme pass type checking. Some of the typings err on the loose side, but should still be really helpful for typescript users.

### CODE REVIEW

**Review by aribouius — COMMENTED** [review]
@nlap this looks great, thanks for the contribution!

I'm happy to merge as is, but I haven't used TS for a couple years so I'd love to get another thumbs up from another user.

@rchavik @timothyjoh thoughts?

**Review by jonahsol — CHANGES_REQUESTED** [review]
This is very helpful. I'll be replacing my `any` riddled definition. Thanks @nlap !

Some suggestions - if you're pressed for time I'd be happy to add these in a PR.

Generic `useQuery` / `useMutation`:

    interface IResult<TData = IStringMap | IStringMap[]> {
        data: TData
    }

    useQuery<TData = IStringMap | IStringMap[]>(...): IResult<TData>

A couple of additional types

    IResult.refetch: () => void
    IConfig.stringify<QueryParams = any>: (q: QueryParams) => string

`IQueryArg` seems like a great place to use TS 4.0 labelled tuples:

    type Falsey = false | undefined | null
    type IQueryArg<QueryParams = any> = Falsey | [
        type: string,
        ...queryKeys: any[],
       queryParams?: QueryParams
    ]

**Comment by nlap** [comment]
Thanks @jonahsol, those are great improvements. l added them in, with a few slight changes, and they're working well on my project. Are you able to take another look?

**Comment by aribouius** [comment]
Great contribution @nlap, and thanks for everyone's input!

**Review by aribouius — APPROVED** [review]

**Comment by aribouius** [comment]
Types are now available as of version `0.0.22`.

**Pull request merged**
